jakarta.persistence.validation.mode=none

hibernate.c3p0.acquireIncrement=1
hibernate.c3p0.acquireRetryAttempts=1
hibernate.c3p0.minSize=1
hibernate.c3p0.maxSize=5

hibernate.jdbc.fetch_size=100

#hibernate.show_sql=true
#hibernate.use_sql_comments=true