-- Task 1: Rename column COMMENT to STANDARDCOMMENT for table STANDARDCOMMENT
ALTER TABLE STANDARDCOMMENT ALTER COLUMN COMMENT RENAME TO STANDARDCOMMENT

-- Task 2: Rename column COMMENT to SURVEYDESCRIPTION for table SURVEY
ALTER TABLE SURVEY ALTER COLUMN COMMENT RENAME TO SURVEYDESCRIPTION

-- Task 3: Rename column COMMENT to STANDARDCOMMENT for table COMMENT
ALTER TABLE COMMENT ALTER COLUMN COMMENT RENAME TO STANDARDCOMMENT

-- Task 4: Rename table COMMENT to OBSERVATIONCOMMENT
ALTER TABLE COMMENT RENAME TO OBSERVATIONCOMMENT

-- Task 5: Set database version to 4
UPDATE DBPARAMETER SET PARVALUE = '4' WHERE PARNAME = 'version'
