CREATE TABLE SCATTEROBJECT (NATION SMALLINT NOT NULL, PLATFORM SMALLINT NOT NULL, SURVEY INTEGER NOT NULL, OBJECT INTEGER NOT NULL, OBSERVATIONDATE INTEGER NOT NULL, OBSERVATIONTIME INTEGER NOT NULL, OBSERVATIONTYPE SMALLINT NOT NULL, DURATION INTEGER NOT NULL, PRIMARY KEY (NATION, PLATFORM, SURVEY, OBJECT))
INSERT INTO OBSERVATIONTYPE VALUES(8000,'ScatterObject dummy')
INSERT INTO OBSERVATIONTYPE VALUES(9000,'ScatterObject School')
INSERT INTO OBSERVATIONTYPE VALUES(10000,'ScatterObject Pelagic')
INSERT INTO OBSERVATION SELECT DISTINCT NATION,PLATFORM,SURVEY,0,0,8000,0,0,0,0 FROM SCATTER
INSERT INTO SCATTEROBJECT SELECT DISTINCT NATION, PLATFORM, SURVEY, OBJECT, 0, 0, 8000, 0 FROM SCATTER
ALTER TABLE SCATTEROBJECT ADD CONSTRAINT FKB6DDE37DDC22A7ED FOREIGN KEY (NATION, PLATFORM, SURVEY, OBSERVATIONDATE, OBSERVATIONTIME, OBSERVATIONTYPE) REFERENCES OBSERVATION
ALTER TABLE SCATTER ADD CONSTRAINT FK71E9C6BE9FC27D64 FOREIGN KEY (NATION, PLATFORM, SURVEY, OBJECT) REFERENCES SCATTEROBJECT
CREATE TABLE SCHOOLCATEGORY (NATION SMALLINT NOT NULL, PLATFORM SMALLINT NOT NULL, SURVEY INTEGER NOT NULL, OBJECT INTEGER NOT NULL, CATEGORYSYSTEM SMALLINT NOT NULL, CATEGORY INTEGER NOT NULL, PRIMARY KEY (NATION, PLATFORM, SURVEY, OBJECT, CATEGORYSYSTEM, CATEGORY))
CREATE TABLE SCHOOLCATEGORYSYSTEM (CATEGORYSYSTEM SMALLINT NOT NULL, CATEGORYSYSTEMNAME VARCHAR(40), CATEGORYSYSTEMDESCRIPTION VARCHAR(40), PRIMARY KEY (CATEGORYSYSTEM))
CREATE TABLE SCHOOLDATA (NATION SMALLINT NOT NULL, PLATFORM SMALLINT NOT NULL, SURVEY INTEGER NOT NULL, OBJECT INTEGER NOT NULL, SCHOOLOBJECTTYPE SMALLINT NOT NULL, TRANSCEIVER INTEGER NOT NULL, FREQUENCY INTEGER NOT NULL, TRANSCEIVERREF INTEGER, FREQUENCYREF INTEGER, SA FLOAT, SL FLOAT, RF FLOAT, RF_SDEV FLOAT, SV_MEAN FLOAT, SV_SDEV FLOAT, SKEWNESS FLOAT, PRIMARY KEY (NATION, PLATFORM, SURVEY, OBJECT, SCHOOLOBJECTTYPE, TRANSCEIVER, FREQUENCY))
CREATE TABLE SCHOOLDETECT (NATION SMALLINT NOT NULL, PLATFORM SMALLINT NOT NULL, SURVEY INTEGER NOT NULL, OBJECT INTEGER NOT NULL, DETECTIONTHRESHOLD FLOAT NOT NULL, DETECTIONTHRESHOLDHOLE FLOAT NOT NULL, MINSIZEHOLE FLOAT NOT NULL, SMOOTHVERTICAL FLOAT NOT NULL, SMOOTHHORIZONTAL FLOAT NOT NULL, DETECTIONSETTINGS VARCHAR(1024) NOT NULL, MANUALLYCORRECTED SMALLINT NOT NULL, PRIMARY KEY (NATION, PLATFORM, SURVEY, OBJECT))
CREATE TABLE SCHOOLMORPHOLOGY (NATION SMALLINT NOT NULL, PLATFORM SMALLINT NOT NULL, SURVEY INTEGER NOT NULL, OBJECT INTEGER NOT NULL, SCHOOLOBJECTTYPE SMALLINT NOT NULL, OBSERVATIONDATE INTEGER, OBSERVATIONTIME INTEGER, BOXDURATION INTEGER, BOXTHICKNESS FLOAT, BOXLENGTH FLOAT, MAXTHICKNESS FLOAT, MAXLENGTH FLOAT, PERIMETER FLOAT, AREA FLOAT, ROUGHNESS FLOAT, CIRCULARITY FLOAT, RECTANGULARITY FLOAT, ELONGATION FLOAT, DISTANCETOBOTTOM FLOAT, DISTANCETOSURFACE FLOAT, BOTTOMDEPTH FLOAT, NMBACOUSTICCAT INTEGER, NMBHOLES INTEGER, NMBKERNELS INTEGER, PRIMARY KEY (NATION, PLATFORM, SURVEY, OBJECT, SCHOOLOBJECTTYPE))
CREATE TABLE SCHOOLOBJECTTYPE (SCHOOLOBJECTTYPE SMALLINT NOT NULL, SCHOOLOBJECTTYPENAME VARCHAR(40), SCHOOLOBJECTTYPEDESCRIPTION VARCHAR(80), PRIMARY KEY (SCHOOLOBJECTTYPE))
ALTER TABLE SCHOOLCATEGORY ADD CONSTRAINT FKDE5B64721F26341A FOREIGN KEY (CATEGORYSYSTEM) REFERENCES SCHOOLCATEGORYSYSTEM
ALTER TABLE SCHOOLCATEGORY ADD CONSTRAINT FKDE5B64729FC27D64 FOREIGN KEY (NATION, PLATFORM, SURVEY, OBJECT) REFERENCES SCATTEROBJECT
ALTER TABLE SCHOOLDATA ADD CONSTRAINT FKFA4D711E1421E8FC FOREIGN KEY (NATION, PLATFORM, SURVEY, OBJECT, SCHOOLOBJECTTYPE) REFERENCES SCHOOLMORPHOLOGY
ALTER TABLE SCHOOLDETECT ADD CONSTRAINT FK9CEE1B179FC27D64 FOREIGN KEY (NATION, PLATFORM, SURVEY, OBJECT) REFERENCES SCATTEROBJECT
ALTER TABLE SCHOOLMORPHOLOGY ADD CONSTRAINT FKD384C510291CAB26 FOREIGN KEY (SCHOOLOBJECTTYPE) REFERENCES SCHOOLOBJECTTYPE
ALTER TABLE SCHOOLMORPHOLOGY ADD CONSTRAINT FKD384C5109FC27D64 FOREIGN KEY (NATION, PLATFORM, SURVEY, OBJECT) REFERENCES SCATTEROBJECT
UPDATE DBPARAMETER SET PARVALUE = '2' WHERE PARNAME = 'version'
