-- Task 1: Rename column COMMENT to STANDARDCOMMENT for table STANDARDCOMMENT
RENAME COLUMN STANDARDCOMMENT.COMMENT TO STANDARDCOMMENT

-- Task 2: Rename column COMMENT to SURVEYDESCRIPTION for table SURVEY
RENAME COLUMN SURVEY.COMMENT TO SURVEYDESCRIPTION

-- Task 3: Rename column COMMENT to STANDARDCOMMENT for table COMMENT
RENAME COLUMN COMMENT.COMMENT TO STANDARDCOMMENT

-- Task 4: Rename table COMMENT to OBSERVATIONCOMMENT
RENAME TABLE COMMENT TO OBSERVATIONCOMMENT

-- Task 5: Set database version to 4
UPDATE DBPARAMETER SET PARVALUE = '4' WHERE PARNAME = 'version'
