package no.imr.korona.apps.relay;

import no.imr.tools.io.FileUtils;

import java.io.IOException;
import java.nio.file.Path;

/**
 * Class for keeping a KoronaRelay-generated *.new file.
 * When calling {@link #move()} the .new suffix is removed.
 */
public final class KoronaRelayUpdate {
   private final KoronaRelayStatus koronaRelayStatus;
   private final Path sourceFile;

   KoronaRelayUpdate(KoronaRelayStatus koronaRelayStatus, Path sourceFile) {
      this.koronaRelayStatus = koronaRelayStatus;
      this.sourceFile = sourceFile;
   }

   /**
    * {@return the source .new file generated by KoronaRelay}
    */
   public Path getSourceFile() {
      return sourceFile;
   }

   /**
    * {@return the destination file}
    */
   public Path getDestinationFile() {
      Path dir = sourceFile.getParent();
      String name = sourceFile.getFileName().toString();
      return dir.resolve(name.substring(0, name.lastIndexOf(KoronaRelay.NEW_SUFFIX)));
   }

   /**
    * Removes the .new suffix from the initial file. It assumes that it is safe to rename
    * this file and that no updates are done to this file since this object
    * was generated. This should be guaranteed by {@link KoronaRelayUpdateChecker},
    * which keeps a lock on the directory from which these objects were created.
    *
    * @throws IOException if some IO error occurs
    */
   public void move() throws IOException {
      try {
         FileUtils.move(sourceFile, getDestinationFile());
      } catch (IOException e) {
         if (FileUtils.notExists(e, sourceFile)) {
            removeThisFromKoronaRelayStatus();
            throw new IOException("File does not exist: " + sourceFile);
         }
         throw e;
      }
      removeThisFromKoronaRelayStatus();
   }

   private void removeThisFromKoronaRelayStatus() {
      koronaRelayStatus.getFilesReadyForCopy().remove(sourceFile);
   }
}
